data_path: "./data"
augmentations: True
store_data_in_ram: True
use_val_for_train: True
seed: 2024

ce:
  # output_dims: 39535
  output_dims: 41616
  weight: 1.0
  gamma: 2

triplet:
  margin: 0.3
  weight: 0.1

center:
  weight: 0.01


aug_params:
  volume: True
  volume_prob: 0.6
  low_volume_coef: 0.5
  high_volume_coef: 1.1

  time_roll: True
  time_roll_prob: 0.6
  min_timeroll_shift_num: -14
  max_timeroll_shift_num: 14

  time_stretch: True
  time_stretch_prob: 0.55
  low_stretch_factor: 0.8
  high_stretch_factor: 1.25

  equalize: True
  equalize_prob: 0.75
  equalize_low_factor: 0.60
  equalize_high_factor: 1.2

  gaussian_noise: True
  gaussian_noise_prob: 0.55
  noise_levels: [0.0, 4.0]

  # mask_silence: True
  mask_silence_prob: 0.1
  pad_value: -80

  # duplicate: True
  duplicate_prob: 0.35


  # time_mask: True
  # time_mask_prob: 1.0
  # num_time_masks: 1
  # time_mask_regionsize: [0.02, 0.20]

  # low_shift: True
  # low_shift_prob: 0.3
  # low_shift_values: [4, 10]


  # random_time_crop: True
  # random_timecrop_prob: 1.0
  # crop_min_chunklen: 25
  # crop_max_chunklen: 50


  # region_val: -80

  # mask_region_num: 4
  # mask_region_size: [0.25, 0.1]

  
file_extension: "npy"
save_model_path: "models"
debug: True
progress_bar: True
device: "cuda:0"
num_channels: 1
# embed_dim: 128
embed_dim: 256
# embed_dim: 512
use_wandb: True

conformer:
  input_dim: 84
  # input_dim: 96
  output_dims: 128
  # attention_dim: 512
  attention_dim: 256
  num_blocks: 6
  # input_layer: conv2d_nosub
  input_layer: conv2d_upsample2



train:
  num_classes: 41616
  warmup: False
  warmup_steps: 400
  dataset_path: "./data/train"
  mixed_precision: True
  triplet_margin: 0.3
  smooth_factor: 0.1
  dropout: 0.1
  model_ckpt:
  batch_size: 128

  num_workers: 0
  shuffle: True
  drop_last: True
  epochs: 25

  learning_rate: 0.001
  adam_b1: 0.8
  adam_b2: 0.99
  lr_decay: 0.99
  min_lr: 0.0001
  lr_update_steps: 1000

  patience: 8
  log_steps: 10
  gamma: 2

val:
  dataset_path: "./data/train"
  save_val_outputs: True
  max_seq_len: -1
  batch_size: 100
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_val"
  val_period: 800

test:
  dataset_path: "./data/test"
  save_test_outputs: True
  # model_ckpt: 
  model_ckpt: "./outputs_val/run-25/model/best-model-epoch=19-max_secs=50.pt"
  max_seq_len: -1
  batch_size: 1
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_test"