data_path: "/home/olisvalue/contests/baseline/data"
augmentations: True
store_data_in_ram: False

aug_params:
  # notes: volume is definetely good augmentation
  # volume: True
  # volume_prob: 1.0
  # roll_pitch: True

  # time_roll: True
  # time_roll_prob: 1.0


  # time_stretch: True
  # time_stretch_prob: 1.0

  # random_erase: True

  mask_silence: True
  mask_silence_prob: 0.1

  # time_masking: True

  # equalize: True
  # equalize_prob: 1.0

  # random_time_crop: True
  # random_timecrop_prob: 1.0

  crop_min_chunklen: 25
  crop_max_chunklen: 50

  low_volume_coef: 0.5
  high_volume_coef: 1.0

  pad_value: -80

  roll_shift_num: 10

  min_timeroll_shift_num: -12
  max_timeroll_shift_num: 12

  region_val: -80

  mask_region_num: 4
  mask_region_size: [0.25, 0.1]

  equalize_low_factor: 0.70
  equalize_high_factor: 1.15

  low_stretch_factor: 0.8
  high_stretch_factor: 1.2

  num_time_masks: 1
  max_time_mask_size: 6

  


seed: 2024

file_extension: "npy"
save_model_path: "models"
debug: True
progress_bar: True
device: "cuda:0"
num_channels: 1
# embed_dim: 2048
# embed_dim: 128
embed_dim: 256
# Осторожно, embed_dim = 128 для Conformer (base)!
use_wandb: True

ce:
  output_dims: 39535
  weight: 1.0
  gamma: 2

triplet:
  margin: 0.3
  weight: 0.1

center:
  weight: 0.01

conformer:
  input_dim: 84
  # input_dim: 96
  output_dims: 128
  # attention_dim: 512
  attention_dim: 256
  num_blocks: 6
  input_layer: conv2d_nosub
  # input_layer: conv2d_upsample4



train:
  warmup: False
  warmup_steps: 400
  dataset_path: "/home/olisvalue/contests/baseline/data/train"
  mixed_precision: True
  num_classes: 39535
  triplet_margin: 0.3
  smooth_factor: 0.1
  dropout: 0.1
  model_ckpt:
  # model_ckpt: "/home/olisvalue/contests/baseline/pretrained.pt"
  batch_size: 256
  # batch_size: 150

  num_workers: 0
  shuffle: True
  drop_last: True
  epochs: 25

  learning_rate: 0.001
  # learning_rate: 0.0009
  adam_b1: 0.8
  adam_b2: 0.99
  lr_decay: 0.97
  # lr_decay: 0.9975 - может быть, увеличить до этого значения?
  min_lr: 0.0001
  # lr_update_steps: 550
  lr_update_steps: 1000
  # надо бы 1000 для conformer

  patience: 4
  log_steps: 10
  gamma: 2

val:
  dataset_path: "/home/olisvalue/contests/baseline/data/train"
  save_val_outputs: True
  max_seq_len: -1
  batch_size: 100
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_val"
  val_period: 470

test:
  dataset_path: "/home/olisvalue/contests/baseline/data/test"
  save_test_outputs: True
  model_ckpt: 
  # model_ckpt: "/home/olisvalue/contests/baseline/best-model-epoch=11-max_secs=50.pt"
  max_seq_len: -1
  batch_size: 1
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_test"
