data_path: "/home/olisvalue/contests/baseline/data"
file_extension: "npy"
save_model_path: "models"
debug: True
progress_bar: True
device: "cuda:0"
num_channels: 1

train:
  dataset_path: "/home/olisvalue/contests/baseline/data/train"
  mixed_precision: True
  num_classes: 39535
  triplet_margin: 0.2
  triplet_importance: 5
  cls_importance: 0.01
  smooth_factor: 0.1
  dropout: 0.1
  model_ckpt: "/home/olisvalue/contests/baseline/outputs_val/run-12/model/best-model-epoch=4-max_secs=50.pt"
  batch_size: 200
  num_workers: 0
  shuffle: True
  drop_last: True
  epochs: 25
  learning_rate: 0.0001
  patience: 4
  log_steps: 10

val:
  dataset_path: "/home/olisvalue/contests/baseline/data/train"
  save_val_outputs: True
  max_seq_len: -1
  batch_size: 200
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_val"

test:
  dataset_path: "/home/olisvalue/contests/baseline/data/test"
  save_test_outputs: True
  model_ckpt: "/home/olisvalue/contests/baseline/outputs_val/run-12/model/best-model-epoch=4-max_secs=50.pt"
  max_seq_len: -1
  batch_size: 1
  num_workers: 0
  shuffle: False
  drop_last: False
  output_dir: "outputs_test"
